---
# Install
- name: Ensure nginx is installed
  apt: pkg={{ item }} state=present
  with_items:
    - nginx
    - python-passlib  # needed for htpasswd
    - htop  # it's handy

# Configure
- name: Configure nginx.conf
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
            owner=root group=root mode=0644
- name: Configure nginx services.conf
  template: src=services.conf.j2 dest=/etc/nginx/services.conf
            owner=root group=root mode=0644
- name: Configure nginx proxy-control.conf
  template: src=proxy-control.conf.j2 dest=/etc/nginx/proxy-control.conf
            owner=root group=root mode=0644
- name: Configure nginx auth-basic.conf
  template: src=auth-basic.conf.j2 dest=/etc/nginx/auth-basic.conf
            owner=root group=root mode=0644
- name: Configure nginx .htpasswd users file
  htpasswd: path=/etc/nginx/.htpasswd name={{ htpasswd_name }}
            password={{ htpasswd_password }}
            owner=root group=root mode=0644
  when: htpasswd_name != "" and htpasswd_password != ""
- name: Generate ssl certificate
  command: openssl req -new -nodes -x509 -subj "/C=US/ST=Oregon/L=Portland/O=IT/CN={{ server_name }}" -days 3650 -keyout {{ nginx_ssl_key }} -out {{ nginx_ssl_cert }} -extensions v3_ca creates={{ nginx_ssl_cert }}

# Start it
- name: Ensure nginx is running
  service: name=nginx state=running enabled=yes
